/* 
 * File:   pinTranslate.h
 * Author: Daniel
 *
 * SUMMARY:
 * this file contains #defines to translate chipKit pins to pic32 pin
 * Created on September 5, 2016, 12:38 PM
 */

#ifndef PINTRANSLATE_H
#define	PINTRANSLATE_H

#ifdef	__cplusplus
extern "C" {
#endif

#define CHIPKIT_0 PORTS_ID_0, PORT_CHANNEL_F, PORTS_BIT_POS_2
#define CHIPKIT_1 PORTS_ID_0, PORT_CHANNEL_F, PORTS_BIT_POS_8
#define CHIPKIT_2 PORTS_ID_0, PORT_CHANNEL_E, PORTS_BIT_POS_8
#define CHIPKIT_3 PORTS_ID_0, PORT_CHANNEL_D, PORTS_BIT_POS_0
#define CHIPKIT_4 PORTS_ID_0, PORT_CHANNEL_C, PORTS_BIT_POS_14
#define CHIPKIT_5 PORTS_ID_0, PORT_CHANNEL_D, PORTS_BIT_POS_1
#define CHIPKIT_6 PORTS_ID_0, PORT_CHANNEL_D, PORTS_BIT_POS_2
#define CHIPKIT_7 PORTS_ID_0, PORT_CHANNEL_E, PORTS_BIT_POS_9
#define CHIPKIT_8 PORTS_ID_0, PORT_CHANNEL_D, PORTS_BIT_POS_12
#define CHIPKIT_9 PORTS_ID_0, PORT_CHANNEL_D, PORTS_BIT_POS_3
#define CHIPKIT_10 PORTS_ID_0, PORT_CHANNEL_D, PORTS_BIT_POS_4
#define CHIPKIT_11 PORTS_ID_0, PORT_CHANNEL_C, PORTS_BIT_POS_4
#define CHIPKIT_12 PORTS_ID_0, PORT_CHANNEL_A, PORTS_BIT_POS_2
#define CHIPKIT_13 PORTS_ID_0, PORT_CHANNEL_A, PORTS_BIT_POS_3
#define CHIPKIT_14 PORTS_ID_0, PORT_CHANNEL_F, PORTS_BIT_POS_13
#define CHIPKIT_15 PORTS_ID_0, PORT_CHANNEL_F, PORTS_BIT_POS_12
#define CHIPKIT_16 PORTS_ID_0, PORT_CHANNEL_F, PORTS_BIT_POS_5
#define CHIPKIT_17 PORTS_ID_0, PORT_CHANNEL_F, PORTS_BIT_POS_4
#define CHIPKIT_18 PORTS_ID_0, PORT_CHANNEL_D, PORTS_BIT_POS_15
#define CHIPKIT_19 PORTS_ID_0, PORT_CHANNEL_D, PORTS_BIT_POS_14
#define CHIPKIT_20 PORTS_ID_0, PORT_CHANNEL_A, PORTS_BIT_POS_15
#define CHIPKIT_21 PORTS_ID_0, PORT_CHANNEL_A, PORTS_BIT_POS_14
#define CHIPKIT_22 PORTS_ID_0, PORT_CHANNEL_C, PORTS_BIT_POS_2
#define CHIPKIT_23 PORTS_ID_0, PORT_CHANNEL_C, PORTS_BIT_POS_3
#define CHIPKIT_24 VBUS
#define CHIPKIT_25 PORTS_ID_0, PORT_CHANNEL_F, PORTS_BIT_POS_3
#define CHIPKIT_26 PORTS_ID_0, PORT_CHANNEL_G, PORTS_BIT_POS_3
#define CHIPKIT_27 PORTS_ID_0, PORT_CHANNEL_G, PORTS_BIT_POS_2
#define CHIPKIT_28 PORTS_ID_0, PORT_CHANNEL_G, PORTS_BIT_POS_15
#define CHIPKIT_29 PORTS_ID_0, PORT_CHANNEL_G, PORTS_BIT_POS_7
#define CHIPKIT_30 PORTS_ID_0, PORT_CHANNEL_E, PORTS_BIT_POS_7
#define CHIPKIT_31 PORTS_ID_0, PORT_CHANNEL_E, PORTS_BIT_POS_6
#define CHIPKIT_32 PORTS_ID_0, PORT_CHANNEL_E, PORTS_BIT_POS_5
#define CHIPKIT_33 PORTS_ID_0, PORT_CHANNEL_E, PORTS_BIT_POS_4
#define CHIPKIT_34 PORTS_ID_0, PORT_CHANNEL_E, PORTS_BIT_POS_3
#define CHIPKIT_35 PORTS_ID_0, PORT_CHANNEL_E, PORTS_BIT_POS_2
#define CHIPKIT_36 PORTS_ID_0, PORT_CHANNEL_E, PORTS_BIT_POS_1
#define CHIPKIT_37 PORTS_ID_0, PORT_CHANNEL_E, PORTS_BIT_POS_0
#define CHIPKIT_38 PORTS_ID_0, PORT_CHANNEL_D, PORTS_BIT_POS_10
#define CHIPKIT_39 PORTS_ID_0, PORT_CHANNEL_D, PORTS_BIT_POS_5
#define CHIPKIT_40 PORTS_ID_0, PORT_CHANNEL_B, PORTS_BIT_POS_11
#define CHIPKIT_41 PORTS_ID_0, PORT_CHANNEL_B, PORTS_BIT_POS_13
#define CHIPKIT_42 PORTS_ID_0, PORT_CHANNEL_B, PORTS_BIT_POS_12
#define CHIPKIT_43 PORTS_ID_0, PORT_CHANNEL_G, PORTS_BIT_POS_8
#define CHIPKIT_44 PORTS_ID_0, PORT_CHANNEL_A, PORTS_BIT_POS_10
#define CHIPKIT_45 PORTS_ID_0, PORT_CHANNEL_F, PORTS_BIT_POS_0
#define CHIPKIT_46 PORTS_ID_0, PORT_CHANNEL_F, PORTS_BIT_POS_1
#define CHIPKIT_47 PORTS_ID_0, PORT_CHANNEL_D, PORTS_BIT_POS_6
#define CHIPKIT_48 PORTS_ID_0, PORT_CHANNEL_D, PORTS_BIT_POS_8
#define CHIPKIT_49 PORTS_ID_0, PORT_CHANNEL_D, PORTS_BIT_POS_11
#define CHIPKIT_50 PORTS_ID_0, PORT_CHANNEL_G, PORTS_BIT_POS_7
#define CHIPKIT_51 PORTS_ID_0, PORT_CHANNEL_G, PORTS_BIT_POS_8
#define CHIPKIT_52 PORTS_ID_0, PORT_CHANNEL_G, PORTS_BIT_POS_6
#define CHIPKIT_53 PORTS_ID_0, PORT_CHANNEL_G, PORTS_BIT_POS_9
#define CHIPKIT_54 PORTS_ID_0, PORT_CHANNEL_B, PORTS_BIT_POS_0
#define CHIPKIT_55 PORTS_ID_0, PORT_CHANNEL_B, PORTS_BIT_POS_1
#define CHIPKIT_56 PORTS_ID_0, PORT_CHANNEL_B, PORTS_BIT_POS_2
#define CHIPKIT_57 PORTS_ID_0, PORT_CHANNEL_B, PORTS_BIT_POS_3
#define CHIPKIT_58 PORTS_ID_0, PORT_CHANNEL_B, PORTS_BIT_POS_4
#define CHIPKIT_59 PORTS_ID_0, PORT_CHANNEL_B, PORTS_BIT_POS_5
#define CHIPKIT_60 PORTS_ID_0, PORT_CHANNEL_B, PORTS_BIT_POS_6
#define CHIPKIT_61 PORTS_ID_0, PORT_CHANNEL_B, PORTS_BIT_POS_7
#define CHIPKIT_62 PORTS_ID_0, PORT_CHANNEL_B, PORTS_BIT_POS_8
#define CHIPKIT_63 PORTS_ID_0, PORT_CHANNEL_B, PORTS_BIT_POS_9
#define CHIPKIT_64 PORTS_ID_0, PORT_CHANNEL_B, PORTS_BIT_POS_10
#define CHIPKIT_65 PORTS_ID_0, PORT_CHANNEL_B, PORTS_BIT_POS_11
#define CHIPKIT_66 PORTS_ID_0, PORT_CHANNEL_B, PORTS_BIT_POS_13
#define CHIPKIT_67 PORTS_ID_0, PORT_CHANNEL_B, PORTS_BIT_POS_12
#define CHIPKIT_68 PORTS_ID_0, PORT_CHANNEL_B, PORTS_BIT_POS_14
#define CHIPKIT_69 PORTS_ID_0, PORT_CHANNEL_B, PORTS_BIT_POS_15
#define CHIPKIT_70 PORTS_ID_0, PORT_CHANNEL_A, PORTS_BIT_POS_0
#define CHIPKIT_71 PORTS_ID_0, PORT_CHANNEL_A, PORTS_BIT_POS_1
#define CHIPKIT_72 PORTS_ID_0, PORT_CHANNEL_A, PORTS_BIT_POS_4
#define CHIPKIT_73 PORTS_ID_0, PORT_CHANNEL_A, PORTS_BIT_POS_5
#define CHIPKIT_74 PORTS_ID_0, PORT_CHANNEL_D, PORTS_BIT_POS_9
#define CHIPKIT_75 PORTS_ID_0, PORT_CHANNEL_C, PORTS_BIT_POS_13
#define CHIPKIT_76 PORTS_ID_0, PORT_CHANNEL_D, PORTS_BIT_POS_13
#define CHIPKIT_77 PORTS_ID_0, PORT_CHANNEL_D, PORTS_BIT_POS_7
#define CHIPKIT_78 PORTS_ID_0, PORT_CHANNEL_G, PORTS_BIT_POS_1
#define CHIPKIT_79 PORTS_ID_0, PORT_CHANNEL_G, PORTS_BIT_POS_0
#define CHIPKIT_80 PORTS_ID_0, PORT_CHANNEL_A, PORTS_BIT_POS_6
#define CHIPKIT_81 PORTS_ID_0, PORT_CHANNEL_A, PORTS_BIT_POS_7
#define CHIPKIT_82 PORTS_ID_0, PORT_CHANNEL_G, PORTS_BIT_POS_14
#define CHIPKIT_83 PORTS_ID_0, PORT_CHANNEL_G, PORTS_BIT_POS_12
#define CHIPKIT_84 PORTS_ID_0, PORT_CHANNEL_G, PORTS_BIT_POS_13
#define CHIPKIT_85 PORTS_ID_0, PORT_CHANNEL_A, PORTS_BIT_POS_9


#ifdef	__cplusplus
}
#endif

#endif	/* PINTRANSLATE_H */

